id: PAC717EAD
initial_creation_type: ocr
source_metadata:
  volumes:
    5a6dfc6d18cb4dcfaed104df92d5a97c:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
